name: CI on Push and Pull Request

on: [push, pull_request]

env:
  SOLUTION_NAME: ToDo-list
  ANDROID_PROJECT_NAME: ToDo-list.Droid

jobs:
 Android:
   name: Android
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@master
     - name: Building APK
       uses: ./action
       with:
         args: /r:True /t:SignAndroidPackage /p:AndroidSdkDirectory=/android/sdk ${{env.SOLUTION_NAME}}/${{env.ANDROID_PROJECT_NAME}}/${{env.ANDROID_PROJECT_NAME}}.csproj
     - name: Artifacts
       run: |
          mkdir -p builds
          cp ${{env.SOLUTION_NAME}}/${{env.ANDROID_PROJECT_NAME}}/bin/Debug/*.apk builds
     - name: Upload Artifacts
       uses: actions/upload-artifact@v1
       with:
         name: builds
         path: builds  
                  
          
 iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        nuget restore
        msbuild ToDo-list/ToDo-list.iOS/ToDo-list.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
